version: '3'

volumes:
  data: {}

services:
  pynlai:
    build:
      context: .
      dockerfile: ./compose/pynlai/Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    image: pynlai
    volumes:
      - .:/app
      - data:/data
